# -*- mode: python -*-

Import("env")

env.InjectThirdPartyIncludePaths('asio')

env.Library(target='task_executor_interface',
            source=['task_executor.cpp',],
            LIBDEPS=[
                '$BUILD_DIR/mongo/db/service_context',
            ])

env.Library(target='network_interface',
            source=['network_interface.cpp',],
            LIBDEPS=[
            ])

env.Library(target='network_interface_impl', # TODO: rename to thread_pool_network_interface
            source=['network_interface_impl.cpp',],
            LIBDEPS=[
                '$BUILD_DIR/mongo/client/remote_command_runner_impl',
                'network_interface',
                # TODO: add dependency on the task executor *interface* once available.
            ])

env.Library('network_interface_mock',
            'network_interface_mock.cpp',
            LIBDEPS=[
                'network_interface',
            ])

env.Library(
    target='network_interface_asio',
    source=[
        'network_interface_asio.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/client/clientdriver',
        '$BUILD_DIR/mongo/db/coredb',
        '$BUILD_DIR/mongo/db/repl/replication_executor',
        '$BUILD_DIR/mongo/db/serveronly',
        '$BUILD_DIR/third_party/shim_asio',
    ])

env.CppUnitTest(
    target='network_interface_asio_test',
    source=[
        'network_interface_asio_test.cpp'
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/util/ntservice_mock',
        'network_interface_asio',
    ],
    NO_CRUTCH=True
)
